version = 0.1

[default.build.parameters]
cached = false
parallel = true

[default.deploy.parameters]
stack_name          = "platform-foundation-prod"
s3_bucket           = "REPLACE_ME_SAM_BUCKET_PROD"
s3_prefix           = "platform-foundation-prod"
region              = "ap-south-1"
capabilities        = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset   = true
fail_on_empty_changeset = false
parameter_overrides = "ProjectName=platform EnvironmentName=prod"
